payload = { 'currUnit': u'IDR',
  'customerInfo': { 'address1': '964 Rama 4 Road',
                    'addressee': 'Dan Happiness',
                    'country': 'Thailand',
                    'email': '',
                    'phone': '081-000-0000',
                    'postalCode': '10500',
                    'province': 'Bangkok'},
  'grossTotal': 400000.0,
  'orderItems': [ { 'itemId': u'FA001',
                    'partnerId': 'planetsports',
                    'qty': 1,
                    'subTotal': 100000.0},
                  { 'itemId': u'FA002',
                    'partnerId': 'planetsports',
                    'qty': 2,
                    'subTotal': 100000.0},
                  { 'itemId': u'FA003',
                    'partnerId': 'planetsports',
                    'qty': 3,
                    'subTotal': 150000.0},
                  { 'itemId': u'FA004',
                    'partnerId': 'planetsports',
                    'qty': 1,
                    'subTotal': 35000.0},
                  { 'itemId': 'Discount',
                    'partnerId': 'planetsports',
                    'qty': 1,
                    'subTotal': -35000.0},
                  { 'itemId': 'Shipping Charges',
                    'partnerId': 'planetsports',
                    'qty': 1,
                    'subTotal': 50000.0}],
  'orderShipmentInfo': { 'address1': u'Sarijadi Bandung',
                         'address2': '',
                         'addressee': u'Fajri Abdillah',
                         'city': u'Bandung',
                         'country': u'ID',
                         'district': u'Sukasari',
                         'phone': u'6587773905',
                         'postalCode': u'40131',
                         'province': u'Jawa Barat',
                         'subDistrict': u'Sukasari'},
  'paymentType': 'NON_COD',
  'shippingType': 'STANDARD_2_4_DAYS'}