PROJECT_DIR='~/Projects/python/acm'
PROJECT_TOKEN_FILE='token.txt'

SHOPEE_PARTNER_ID='123'
SHOPEE_SHOP_ID='planet-sport'
SHOPEE_SECRET_KEY='123123123'

ACOMMERCE_USERNAME='clasense4'
ACOMMERCE_API_KEY='3c5afbdb-2cfe-4bd5-b77f-fc0aea2b4e76'
ACOMMERCE_USER_AGENT='Fajri-Abdillah'